{
    "caption" : "Ruby 1.9.3",
    "cmd": ["rvm use 1.9.3;", "ruby", "--",  "$file"],
    "selector": "^.*\\.(ruby|rb)$",
    "env": {
        "ruby_PATH" : "$project_path/../npm_global/lib/ruby_modules"
    },
    "info": "Your code is running at \\033[01;34m$hostname\\033[00m.\n"
        + "\\033[01;31mImportant:\\033[00m use \\033[01;32mENV['PORT']\\033[00m as the port and \\033[01;32mENV['IP']\\033[00m as the host in your scripts!\n"
}